name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to build (leave blank for the branch's latest commit)"
        required: true
        default: ""

env:
  PREMAKE_GENERATOR: vs2022
  BUILD_CONFIGURATION: Final
  BUILD_PLATFORM: Win32

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.commit_sha != '' && github.event.inputs.commit_sha || github.ref }}

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86

      - name: Generate project files (Premake)
        run: >
          tools/premake5.exe ${{ env.PREMAKE_GENERATOR }}
          --MM1_GAME_DIRECTORY="${{ github.workspace }}/builds/"

      - name: Build
        run: >
          msbuild /verbosity:minimal /nologo /m
          /p:Configuration="${{ env.BUILD_CONFIGURATION }}"
          /p:Platform="${{ env.BUILD_PLATFORM }}"
          "build/Open1560.sln"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Open1560-builds
          path: builds
          if-no-files-found: error
